import Head from "next/head";
import Catagory from "../Components/Catagory";
import style from "../styles/Home.module.css";
export default function Home() {
  return (
    <div className="border-2 border-black h-auto">
      <Head>
        <title>E-kart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <div className="grid justify-center">
          <div className={`${style.bannerImg}   grid text-center`}>
            <img
              src="https://m.media-amazon.com/images/I/71qid7QFWJL._SX3000_.jpg"
              alt="img"
              className={`${style.bannerImg} `}
            />
          </div>

          <div className="flex flex-wrap absolute top-36 md:top-60 xl:ml-20 xl:top-3/4 z-10 ">
            <Catagory />
            <Catagory />
            <Catagory />
            <Catagory />
          </div>
        </div>
      </main>
    </div>
  );
}
